kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    tier: backend
- role: worker
  labels:
    tier: frontend
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "172.20.0.0/16"
  serviceSubnet: "172.21.0.0/16"