- name: Update apt
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  become: true
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg

- name: Add keyrings
  become: true
  command: install -m 0755 -d /etc/apt/keyrings

- name: get keyring
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository
  become: true
  apt_repository:
    filename: docker.list
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
