- name: Install pip packages
  pip:
    name:
      - kubernetes
    state: present

#############
#
# Get Kind started
#
#############

- name: Download kind
  get_url:
    url: "{{ kind_url }}"
    dest: /usr/local/bin/kind
    mode: 0755

- name: Copy cluster config
  template:
    src: clusterconfig.yml.j2
    dest: /tmp/clusterconfig.yml

- name: Destroy cluster
  command: kind delete cluster --name {{ cluster_name }}
  ignore_errors: true

- name: Create cluster
  command: kind create cluster --config /tmp/clusterconfig.yml --name {{ cluster_name }}

- name: Present kubeconfig to output
  command: kind get kubeconfig --name {{ cluster_name }}
  register: kubeconfig

#############
#
# Get kubeconfig on local machine
#
#############

- name: Create .kube if not exists
  become: false
  delegate_to: localhost
  file:
    path: ~/.kube
    state: directory

- name: Clean kubeconfig
  become: false
  delegate_to: localhost
  file:
    path: ~/.kube/config.thmkind
    state: absent

- name: Copy kubeconfig to local
  become: false
  delegate_to: localhost
  copy:
    content: "{{ kubeconfig.stdout }}"
    dest: ~/.kube/config.thmkind

- name: Copy kubeconfig to remote for future scripts
  copy:
    content: "{{ kubeconfig.stdout }}"
    dest: /root/.kube/config

- name: Replace IP
  become: false
  delegate_to: localhost
  replace:
    path: ~/.kube/config.thmkind
    regexp: "0.0.0.0"
    replace: "{{ ansible_default_ipv4.address }}"

- name: Replace CA
  become: false
  delegate_to: localhost
  replace:
    path: ~/.kube/config.thmkind
    regexp: "certificate-authority-data.*"
    replace: "insecure-skip-tls-verify: true"
