- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - python3-pip

- name: Install pip packages
  pip:
    name:
      - requests
    state: present

- name: Add apt_key
  block:
    - name: Docker Repo
      get_url: 
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add repository
      apt_repository:
        filename: docker.list
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
        state: present

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes