- name: Determine if Docker is installed.
  stat:
    path: /usr/bin/docker
  register: docker_installed
- name: get install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/install-docker.sh
    mode: 0777
  when: docker_installed.stat.exists == False
- name: install docker
  command: /tmp/install-docker.sh
  when: docker_installed.stat.exists == False
- name: add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  when: docker_installed.stat.exists == True
- name: clean files
  file:
    path: /tmp/install-docker.sh
    state: absent
